# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class authenticationMethod(str, enum.Enum):
    """
    The default is METHOD_NONE
    """

    METHOD_NONE = "METHOD_NONE"
    METHOD_TOKEN = "METHOD_TOKEN"
    METHOD_OIDC = "METHOD_OIDC"
    METHOD_KUBERNETES = "METHOD_KUBERNETES"

    def visit(
        self,
        method_none: typing.Callable[[], T_Result],
        method_token: typing.Callable[[], T_Result],
        method_oidc: typing.Callable[[], T_Result],
        method_kubernetes: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is authenticationMethod.METHOD_NONE:
            return method_none()
        if self is authenticationMethod.METHOD_TOKEN:
            return method_token()
        if self is authenticationMethod.METHOD_OIDC:
            return method_oidc()
        if self is authenticationMethod.METHOD_KUBERNETES:
            return method_kubernetes()
