# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class RolloutType(str, enum.Enum):
    UNKNOWN_ROLLOUT_TYPE = "UNKNOWN_ROLLOUT_TYPE"
    SEGMENT_ROLLOUT_TYPE = "SEGMENT_ROLLOUT_TYPE"
    THRESHOLD_ROLLOUT_TYPE = "THRESHOLD_ROLLOUT_TYPE"

    def visit(
        self,
        unknown_rollout_type: typing.Callable[[], T_Result],
        segment_rollout_type: typing.Callable[[], T_Result],
        threshold_rollout_type: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is RolloutType.UNKNOWN_ROLLOUT_TYPE:
            return unknown_rollout_type()
        if self is RolloutType.SEGMENT_ROLLOUT_TYPE:
            return segment_rollout_type()
        if self is RolloutType.THRESHOLD_ROLLOUT_TYPE:
            return threshold_rollout_type()
