# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic

from ....core.datetime_utils import serialize_datetime
from .rollout_segment import RolloutSegment
from .rollout_threshold import RolloutThreshold
from .rollout_type import RolloutType


class Rollout(pydantic.BaseModel):
    id: str
    namespace_key: str = pydantic.Field(alias="namespaceKey")
    flag_key: str = pydantic.Field(alias="flagKey")
    type: RolloutType
    rank: int
    description: str
    created_at: dt.datetime = pydantic.Field(alias="createdAt")
    updated_at: dt.datetime = pydantic.Field(alias="updatedAt")
    segment: typing.Optional[RolloutSegment]
    threshold: typing.Optional[RolloutThreshold]

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        allow_population_by_field_name = True
        json_encoders = {dt.datetime: serialize_datetime}
