# This file was auto-generated by Fern from our API Definition.

from .types import Segment, SegmentCreateRequest, SegmentList, SegmentMatchType, SegmentUpdateRequest

__all__ = ["Segment", "SegmentCreateRequest", "SegmentList", "SegmentMatchType", "SegmentUpdateRequest"]
